server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.100.98.247:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ZXyy2627@


mybatis-plus:
  mapper-locations: classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0